microsoft/opensource.microsoft.com

_projects/fluentui.md
assets/images/projects/fluentui.svg

Requesting to add the open source Fluent UI projects to this listing. The projects include open source UX libraries across React, Web Components, React Native, iOS & macOS, and Android. Feel free to reach out for any other information.

Adding Fluent UI projects

---

collaborate.html

Updating the phrasing on the [get involved page](https://opensource.microsoft.com/collaborate/) to match that on the main [index page](https://opensource.microsoft.com/)

Change "first good issue" to "good first issue"

---

_projects/fluid-framework.md

Add Fluid to opensource.microsoft.com

---

_projects/forge.md

Forge backs several core services in Azure, and is growing in adoption outside of Microsoft as well. I would love to see it get more visibility in the Microsoft opensource community. Please follow up here or offline for more details. Thanks!

Adding Forge project

---

_includes/credits-faq.html

Fixing typo on Azure credits FAQ

Fix typo on FAQ

---

code-of-conduct.html

Hey,
There is just a small change.

Fix a typo

---

_projects/powertoys.md

Fixes microsoft/opensource.microsoft.com#158

---

_projects/pr-metrics.md

Updating PR Metrics definition with updated URL and description.

Updating PR Metrics definition

---

_projects/sonic.md
_projects/vfs-for-git.md

Looks like these two links were broken.  Please verify that I have found the correct link to replace them.

Fixing broken links

---

package-lock.json

ansi-regex is vulnerable to Inefficient Regular Expression Complexity which could lead to a denial of service.
**CVE-2021-3807**
`7.5/ 10`

Patched Inefficient Regular Expression Complexity in chalk/ansi-regex

---

code-of-conduct-faq.html

Spec: https://ospo.visualstudio.com/OSPO/_workitems/edit/15994?src=WorkItemMention&src-action=artifact_link
-Removing accordians per A11y specs

Removing FAQ accordions per A11y specs

---

.github/workflows/stale.yml

* Never close PRs
* Never close issues with label "bug", "dependency" and "accessibility".
* Also shorten the time until an issue is closed.

Update stale bot configuration

---

_includes/header.html
code-of-conduct-faq.html

Fix: Update path for proper reference to Microsoft logo

---

code-of-conduct.html

Added class to links so they are underlined to meet accessibility requirements

Fix accessibility bug related to links at bottom of page

---

_includes/program-overview.html

Updating figures such as our GitHub Enterprise Cloud use and OpenChain version.

Updating Program Overview page

---

program.html

Update number of components used per month and slightly change wording to be more positive.

Update number of components used per month

---

_data/cocfaq.yml

Accessibility fix: COC FAQ page

---

_includes/footer.html

accessibility fix

---

_dev/scss/layout/_footer.scss
_includes/footer.html

trying to fix footer alignment issue in ff and chrome

---

cla.html

Since we continue to find CCLAs do not scale, we should not encourage it here.

CCLA message

---

_includes/credits-faq.html

Adding note about account and credit card.

Credits page FAQ

---

_includes/credits-overview.html

Updating word to clarify the renewable terms, since we've had some more questions lately.

Credits overview page

---

_projects/hyperlight.md

This PR is to add Hyperlight in the Featured Projects page under Open@Microsoft: https://opensource.microsoft.com/projects/

Create hyperlight.md under Featured Projects

---

.github/workflows/build.yml

Build the next dev site for now.

Add `next` branch

---

.github/workflows/build.yml

Workflow: adding explicit permissions block

---

.github/workflows/build.yml

Updating the instrumentation key used on the site.

1DS update

---

package-lock.json
package.json

v11 primitives is not a compatible peer dependency.

Primer: walking back to v10.x primitives to fix build

---

src/app/azure-credits/page.tsx
src/app/program/page.tsx

Accessibility fix: tablist

---

.github/workflows/build.yml

Also storing static files in blob.

Snap to blob storage as well

---

.github/workflows/build.yml

Build: only publish to blob
